import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TransparentBackground } from "ui";
import { TrpcProvider } from "./_trpc/trpc-provider";
import { RecoilContextProvider } from "./recoil-context-provider";

export const revalidate = 0;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.ReactNode {
  return (
    <html lang="en" className="bg-neutral-900 text-white">
      <body className={inter.className} style={{ userSelect: "none" }}>
        <RecoilContextProvider>
          <TrpcProvider>
            <TransparentBackground>{children}</TransparentBackground>
          </TrpcProvider>
        </RecoilContextProvider>
      </body>
    </html>
  );
}
