name: Deploy Algohub Backend

on:
  push:
    paths:
      - "apps/server/**"
      - "packages/database/**"
      - "packages/problems/**"
      - "packages/types/**"
      - "packages/utils/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          ssh -t -i keyfile ubuntu@ec2-43-204-102-38.ap-south-1.compute.amazonaws.com "sudo bash /home/ubuntu/algo-hub/deploy.sh"
